     apiVersion: apps/v1
     kind: Deployment
     metadata:
       name: springapp-deployment
     spec:
       replicas: 2
       selector:
         matchLabels:
           app: springapp
       template:
         metadata:
           labels:
             app: springapp
         spec:
           containers:
           - name: springapp
             image: gautadas/myfirstjavamavenwebapp:v1.0.0
             imagePullPolicy: Never
             ports:
             - containerPort: 8081
