     apiVersion: v1
     kind: Service
     metadata:
       name: springapp-service
     spec:
       selector:
         app: springapp
       ports:
       - protocol: TCP
         port: 80
         targetPort: 8081
       type: NodePort
